- hosts: arcadia.house
  roles:
    - role: storage_network_host
      tags: [ storage ]
    - role: docker
      tags: [ docker ]
    - role: kubernetes
      tags: [ kubernetes ]
    - role: music_server
      tags: [ music ]
  tasks:
    - copy: src=files/iptables dest=/etc/sysconfig/iptables
    - copy: src=files/resolv.conf dest=/etc/resolv.conf
  handlers:
    - name: reload iptables
      service: name=iptables state=restarted
      notify: reload libvirt networks
    - name: reload libvirt networks
      shell: "virsh net-destroy default; virsh net-start default"
