- hosts: arcadia.house
  tags:
    - packages
  tasks:
    - yum: name={{item}} state=latest
      with_items:
        - git

- hosts: arcadia.house
  tags:
    - sysctl
    - sysconfig
  tasks:
    - name: install sysctl files
      copy: src=files/{{item}} dest=/etc/sysctl.d/{{item}}
      with_items:
        - inotify.conf
      notify: reload sysctl
  handlers:
    - name: reload sysctl
      service: name=systemd-sysctl state=restarted

- hosts: arcadia.house
  tags:
    - filesystems
    - sysconfig
  tasks:
    - name: mount music data
      mount: fstype=ext4 name=/data/music src=/dev/tank/music state=mounted
            opts=rw,relatime
    - name: mount photos data
      mount: fstype=ext4 name=/data/photos src=/dev/tank/photos state=mounted
            opts=rw,relatime
    - name: mount backup data
      mount: fstype=ext4 name=/data/backup src=/dev/tank/backup state=mounted
            opts=rw,relatime
    - name: mount graphite data
      mount: fstype=ext4 name=/data/graphite src=/dev/tank/graphite state=mounted
            opts=rw,relatime

- hosts: arcadia.house
  tags:
    - network
  roles:
    - role: storage_network_host
  tasks:
    - copy: src=files/iptables dest=/etc/sysconfig/iptables
    - copy: src=files/resolv.conf dest=/etc/resolv.conf
    - copy: src=files/ifcfg-{{item}}
            dest=/etc/sysconfig/network-scripts/ifcfg-{{item}}
      with_items:
        - br0
        - br1
  handlers:
    - name: reload iptables
      service: name=iptables state=restarted
      notify: reload libvirt networks
    - name: reload libvirt networks
      shell: "virsh net-destroy default; virsh net-start default"

- hosts: arcadia.house
  tags:
    - docker
  roles:
    - role: docker

- hosts: arcadia.house
  tags:
    - kubernetes
  roles:
    - role: kubernetes

- hosts: arcadia.house
  tags:
    - stats
  roles:
    - role: collectd
    - role: graphite
    - role: kubernetes_service
      services:
        - id: graphite-web
          config: graphite-web-service.yaml
        - id: graphite-carbon
          config: graphite-carbon-service.yaml
    - role: kubernetes_pod
      pods:
        - id: graphite
          config: graphite-pod.yaml

- hosts: arcadia.house
  tags:
    - music
  roles:
    - role: music_server
    - role: kubernetes_service
      services:
        - id: squeezebox-web
          config: squeezebox-web-service.yaml
        - id: squeezebox-player
          config: squeezebox-player-service.yaml
        - id: squeezebox-cli
          config: squeezebox-cli-service.yaml
        - id: squeezebox-slimproto
          config: squeezebox-slimproto-service.yaml
    - role: kubernetes_pod
      pods:
        - id: squeezebox
          config: squeezebox-pod.yaml

- hosts: arcadia.house
  tags:
    - backup
  roles:
    - role: backup_server
    - role: kubernetes_service
      services:
        - id: crashplan-backups
          config: crashplan-backups-service.yaml
        - id: crashplan-mgmt
          config: crashplan-mgmt-service.yaml
    - role: kubernetes_pod
      pods:
        - id: crashplan
          config: crashplan-pod.yaml

