- name: restart kubernetes
  service: name={{item}} state=restarted
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-proxy
    - kubelet
- name: restart kube-ip-manager
  service: name=kube-ip-manager state=restarted
