- name: install kubernetes package(s)
  yum: name={{item}} state=latest
  with_items:
    - kubernetes
  notify: restart kubernetes
- name: install kiwi systemd unit
  copy: src=kiwi.service
        dest=/etc/systemd/system/kiwi.service
  notify: reload systemd
- meta: flush_handlers
- name: activate kubernetes service(s)
  service: name={{item}} state=running enabled=true
  with_items:
    - etcd
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-proxy
    - kubelet
    - kiwi
- name: create directory for kubernetes yaml files
  file: path=/etc/kubernetes/yaml state=directory
- name: create parent for hostdir volume mounts
  file: path=/data state=directory

