- name: install kubernetes package(s)
  yum: name={{item}} state=latest
  with_items:
    - kubernetes
    - python-netaddr
    - python-requests
  notify: restart kubernetes
- name: fetch kube-ip-manager repository
  git: repo=http://github.com/larsks/kube-ip-manager.git
        dest=/root/kube-ip-manager
        update=yes
        version=cluster
  register: update_kube_ip_manager
- name: install kube-ip-manager
  command: python setup.py install
  args:
    chdir: /root/kube-ip-manager
  notify: restart kube-ip-manager
- name: install kube-ip-manager systemd unit
  copy: src=kube-ip-manager.service
        dest=/etc/systemd/system/kube-ip-manager.service
  notify: reload systemd
- meta: flush_handlers
- name: activate kubernetes service(s)
  service: name={{item}} state=running enabled=true
  with_items:
    - etcd
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-proxy
    - kubelet
    - kube-ip-manager
- name: create directory for kubernetes yaml files
  file: path=/etc/kubernetes/yaml state=directory
- name: create parent for hostdir volume mounts
  file: path=/data state=directory

