- name: install kubernetes configs
  copy: src={{item}} dest=/etc/kubernetes/yaml/{{item}}
  with_items:
    - graphite-pod.yaml
    - graphite-web-service.yaml
    - graphite-carbon-service.yaml
    - graphite-statsd-service.yaml
