kind: Pod
id: squeezebox
apiVersion: v1beta1
labels:
  name: squeezebox
desiredState:
  manifest:
    version: v1beta1
    id: squeezebox
    containers:
      - name: squeezebox
        image: larsks/logitech-media-server
        ports:
          - containerPort: 9000
          - containerPort: 9090
          - containerPort: 3483
        env:
          - name: TZ
            value: EST5EDT
        volumeMounts:
          - mountPath: "/srv/itunes"
            name: "itunes"
          - mountPath: "/srv/other"
            name: "other"
          - mountPath: "/srv/squeezebox"
            name: "squeezebox"
    volumes:
      - name: "itunes"
        source:
          hostDir:
            path: /data/music/itunes
      - name: "other"
        source:
          hostDir:
            path: /data/music/other
      - name: "squeezebox"
        source:
          hostDir:
            path: /data/music/squeezebox


